### ISSUE TITLE
[BUG] Nginx OCSP Resolver Related Error

### ISSUE THREAD

**Issue by capitangiaco** [Zer0CoolX/guacamole-install-rhel#112] opened 2020-04-14 10:24 UTC
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y/N
2. You have read the wiki and followed its guidelines including requirements, troubleshooting, etc.? Y

**Details**
CentOS Linux release 7.7.1908 (Core)

**Describe the bug**
there is a problem resolving the letsencrypt ocsp server

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
2020/04/14 10:30:50 [error] 2361#2361: OCSP responder timed out (110: Connection timed out) while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, peer: 92.123.180.202:80, certificate: "/etc/nginx/guacamole.crt"
2020/04/14 10:36:04 [warn] 2361#2361: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/guacamole.crt"

**Have You Found a Solution to the Issue?**
Added:
resolver 1.1.1.1 8.8.8.8 valid=86400s;
resolver_timeout 5s;
in /etc/nginx/conf.d/guacamole_ssl.conf:              

=

**Comment by Zer0CoolX** [comment] 2020-04-14 20:45
To make sure I am understanding correct, you added the following lines to the guacamole_ssl.conf file and it resolved the issue you had?

```
resolver 1.1.1.1 8.8.8.8 valid=86400s;
resolver_timeout 5s;
```

Note: to anyone else finding thi: 8.8.8.8 is Google's "Public" DNS server and 1.1.1.1 is a Cloudflare's Public DNS server. You may choose to use another DNS provider or you may choose to use your own. As long as the domain or IP provided for this parameter can resolve public domains then it should work for its intended purpose. 

Other then the error log, what symptoms alerted you to the problem? Would the site not load, Error when loading the page, SSL cert error in the browser, etc?

This is strange as those parameters have not been a part of the config and it has worked until this point. I am wondering if this is due to a change in Nginx, certbot and/or Lets Encrypt or if its specific to your setup.

A quick search online indicates similar errors over the last several years so the error itself is not new (though the cause in this case could be).

I will have to do some testing and see if I can replicate the problem. Please answer my previous questions in this reply and provide any additional info you can think of (options selected when running the script, any special circumstances that may apply to you and not others, etc.)

If I find something I will report back. It may be that adding the parameter to the config is the solution to this, tho I would want to do so in a way that allows users to choose what domain/IP(s) they use for this purpose.

**Comment by capitangiaco** [comment] 2020-04-14 22:28
I checked the nginx error.log at the time of the installation (15 march) and the warn about the resolver was present (but not the error, and all browsers worked).

This morning (14 April) Firefox cannot access the site (no problems with other browsers), and the error 'OCSP responder timed' out appeared in the logs.
The Firefox error was: MOZILLA_PKIX_ERROR_REQUIRED_TLS_FEATURE_MISSING
https://support.mozilla.org/en-US/questions/1149911
https://medium.com/@alexeysamoshkin/how-ssl-certificate-revocation-is-broken-in-practice-af3b63b9cb3

Setting 'security.ssl.enable_ocsp_must_staple' to false in Firefox config solved the problem without touch the server.
While after put the resolver line in the conf and restarted nginx, Firefox can access Guacamole.
(error.log stopped to show warns and errors)

To try to reproduce the error I removed the resolver line.
the error log started to warn again:
2020/04/14 23:48:35 [warn] 25391#25391: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/guacamole.crt"
But Firefox can access Guacamole without problems and no error 'OCSP responder timed' isn't appeared in the logs.
Probabily Firefox check the revocation of the certificater through the ocsp server only at certain time intervals.

**Comment by Zer0CoolX** [comment] 2020-04-15 03:20
Thank you for reporting this, it seems to be limited to Firefox (for now).

My first effort to resolve this (pun intended) will be to try and hard code the config to simply use the host DNS addresses.

Later (or if the quick fix does not work) I will add a menu option for users to provide resolver domains/IP's from the menu(s).

It could be a few days until I work out a fix for this (the quick fix). In the meantime people should update the file `/etc/nginx/conf.d/guacamole_ssl.conf` to include 2 lines:

```
resolver x.x.x.x valid=xs;
resolver_timeout xs;
```
and replacing the x's with proper values.

For resolver, the IP or domain name of a DNS server, likey the same you use for the server itself (name server in `/etc/resolv.conf`) or a popular upstream like 8.8.8.8, 1.1.1.1, etc.

for valid=xs, replace x with a integer (whole number) representing seconds. Until I know more, I recommend 30s as thats what the official documentation uses as an example.

resolver_timeout defaults to 30s, so that is likely a safe value as well.

I do NOT recommend disabling the setting in Firefox that checks for this as that would affect all sites and potentially circumvent safety measures.

I will respond back when I know more. Thanks

**Comment by Zer0CoolX** [comment] 2020-04-16 20:54
I have started work on a fix for the matter in the testing repo: https://github.com/Zer0CoolX/guacamole-install-rhel/blob/testing-resolver-fix/guac-install.sh

This is as of yet untested, I plan to test it later today and verify it works as expected. Feel free to try it on a test system if you like to see if it resolves the matter for you.

Basically I run a command to pull the hosts nameserver values from resolv.conf, if none are present I use some defaults provided by a variable in the script.

Once I verify its effective, I will merge it to main so people no longer need to manually adjust the guacamole_ssl.conf with the lines.

Thanks again for reporting this.

**Comment by Zer0CoolX** [comment] 2020-04-17 04:13
It looks like my approach worked. No more issue in Firefox. Merged it to main repo. If you find it does not work re-open this issue or start a new one. Thanks.

**Closed by Zer0CoolX** 2020-04-17 04:13 UTC
Labels: bug
