### ISSUE TITLE
[BUG] LDAPS - keytool command not formed properly?

### ISSUE THREAD

**Issue by justsomeusername2020** [Zer0CoolX/guacamole-install-rhel#100] opened 2020-02-11 23:02 UTC
Greetings,

In the newest version of "guac-install.sh" are you certain that the syntax of the keytool command on line 1494 (and 1495) is correct?

Line 1494: keytool -storepasswd -new ${JKS_CACERT_PASSWD} -keystore ${KS_PATH} -storepass "changeit"

I've run the script on Cent OS 7.7 with the option to use LDAP as primary auth method, and it works perfectly every time. But as soon as I choose the option to enable LDAPS, the install script fails at line 1494.

At first, the script error complained that "keytool -storepasswd" is not a valid option. So I updated it to read "keytool -storepass", and then the script continued a little further. But now, I get the following error message in the script running log:

_#### tail end of my script log file #####

Setup_ the LDAP Extension

-Updating guacamole.properties file for LDAP...    

-Updating guacamole.properties file for LDAPS...    
Illegal option:  guacamole
Key and Certificate Management Tool

Commands:

 -certreq            Generates a certificate request
 -changealias        Changes an entry's alias
 -delete             Deletes an entry
 -exportcert         Exports certificate
 -genkeypair         Generates a key pair
 -genseckey          Generates a secret key
 -gencert            Generates certificate from a certificate request
 -importcert         Imports a certificate or a certificate chain
 -importpass         Imports a password
 -importkeystore     Imports one or all entries from another keystore
 -keypasswd          Changes the key password of an entry
 -list               Lists entries in a keystore
 -printcert          Prints the content of a certificate
 -printcertreq       Prints the content of a certificate request
 -printcrl           Prints the content of a CRL file
 -storepasswd        Changes the store password of a keystore

Use "keytool -command_name -help" for usage of command_name

%%% ERROR (Script Failed) | Line 1494 | Command: keytool -storepass -new guacamole -keystore /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.241-2.6.20.0.el7_7.x86_64/jre/lib/security/cacerts /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/lib/security/cacerts -storepass changeit | Exit code: 1 %%%

#######

So, I figured I'll ask if the keytool command on line 1494 & 1495 are constructed properly.

Thanks in advance!

**Comment by Zer0CoolX** [comment] 2020-02-12 19:01
> So, I figured I'll ask if the keytool command on line 1494 & 1495 are constructed properly.

It so far has been. So unless the keytool command was altered in a significant way from CentOS repos it should work. In your output you can even see:

> Commands:
> ...
> -importpass Imports a password
> -importkeystore Imports one or all entries from another keystore
> -**keypasswd** Changes the key password of an entry

so `keypasswd` is obviously a valid switch. as for

> In the newest version of "guac-install.sh" are you certain that the syntax of the keytool command on line 1494 (and 1495) is correct?

Truthfully, no. As mentioned, it has been correct for some time. However I have lost the ability in the last few months to actually test with LDAPS. I plan to eventually setup infrastructure in my test environment to allow this again but for now I have no way to testing it.

Also, looking at your output (specifically the error from my script) I am wondering if its normal for java 1.7.0 AND java 1.8.0 to be on the system and if it should be using 1.7.0 at all. I will have to check on my end and see if those paths (1.7.0 and 1.8.0) also show for me or if they should all be 1.8.0. Ill comment back what I find.

Did you run this script on a clean/fresh install of CentOS with nothing else installed and without having run this script multiple times? Be aware that the script is meant to be run on a clean install with no other software pre-installed or configured first.

Let me know if you find any additional info, fixes, errors, etc.

**Comment by justsomeusername2020** [comment] 2020-02-12 20:06
Yes, this is a clean/fresh install of CentOS. I first ran a "sudo yum update" to update all packages before I ran the install script. Note that "sudo yum update" does not remove old packages by default (which is not recommended as it can break things), you need to include the yum option explicitly:

[admin@localhost jvm]$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

So for java, the old packages are installed by default:
admin@localhost Documents]$ cd /usr/lib/
alsa/           firewalld/      java/           jvm/            kernel/         NetworkManager/ systemd/        
binfmt.d/       firmware/       java-1.5.0/     jvm-commmon/    locale/         polkit-1/       tmpfiles.d/     
crda/           fontconfig/     java-1.6.0/     jvm-exports/    modprobe.d/     python2.7/      tuned/          
cups/           games/          java-1.7.0/     jvm-private/    modules/        rpm/            udev/           
debug/          gcc/            java-1.8.0/     kbd/            modules-load.d/ sse2/           yum-plugins/    
dracut/         grub/           java-ext/       kdump/          mozilla/        sysctl.d/      



Yes, it does look like its normal for java 1.7.0 and 1.8.0 to be installed. I did not touch the java packages other than what is installed from the default installation and by "yum update":

[admin@localhost jvm]$ sudo yum list installed | grep java
[sudo] password for admin: 
java-1.7.0-openjdk.x86_64                   1:1.7.0.241-2.6.20.0.el7_7 @updates 
java-1.7.0-openjdk-headless.x86_64          1:1.7.0.241-2.6.20.0.el7_7 @updates 
java-1.8.0-openjdk.x86_64                   1:1.8.0.242.b08-0.el7_7    @updates 
java-1.8.0-openjdk-headless.x86_64          1:1.8.0.242.b08-0.el7_7    @updates 
javamail.noarch                             1.4.6-8.el7                @base    
javapackages-tools.noarch                   3.4.1-11.el7               @anaconda
python-javapackages.noarch                  3.4.1-11.el7               @anaconda
tzdata-java.noarch                          2019c-1.el7                @updates 

[admin@localhost jvm]$ rpm -qa | grep java
javamail-1.4.6-8.el7.noarch
java-1.7.0-openjdk-headless-1.7.0.241-2.6.20.0.el7_7.x86_64
tzdata-java-2019c-1.el7.noarch
java-1.8.0-openjdk-headless-1.8.0.242.b08-0.el7_7.x86_64
java-1.7.0-openjdk-1.7.0.241-2.6.20.0.el7_7.x86_64
javapackages-tools-3.4.1-11.el7.noarch
java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64
python-javapackages-3.4.1-11.el7.noarch
[admin@localhost jvm]$ cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)



Can you elaborate what the intention of lines 1490-1500 are supposed to do? 
I'm guessing that line 1494 is supposed to create a new java keystore in /usr/lib/jvm/, then line 1495 is supposed to import the user defined SSL certificate (from their AD server) into the keystore.

If so, then line 1494 does not appear to be constructed correctly, it needs to use the restore commands plus options for creating a new keystore.



As a test, I could comment out lines 1491-1500, and run the script, and then afterwards manually create the new key store and and import the certificate. (And I would also manually add line 1497 to the guac properties file of course). 

If LDAPS shows to be working thereafter, (I'll verify using a Wireshark capture), then I'll provide the new keystore commands that worked and you can update the script.

But first I need to know the original inention of what said lines were intended to do...


Thanks!

**Comment by justsomeusername2020** [comment] 2020-02-12 20:30
Hello again,

I believe my last response is exactly what your script is intending to do...

Guacamole is a java web application running on a Tomcat instance, and so when connecting to the AD server to establish a LDAPS connection, the public SSL certificate from the AD domain controller must be added to Guacamole's JVM truststore in order for Tomcat to trust the AD certificate and initiate the SSL/TLS exchange.

Example:
https://confluence.atlassian.com/kb/how-to-import-a-public-ssl-certificate-into-a-jvm-867025849.html

I'm going to try and manually fetch my Active Directory server's SSL cert via the CentOS shell using this command:

openssl s_client -connect google.com:443 -servername google.com:443 < /dev/null | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > public.crt

And then import it using this command:

<JAVA_HOME>/bin/keytool -import -alias <server_name> -keystore <JAVA_HOME>/jre/lib/security/cacerts -file public.crt

If this works, then you could simply the steps required for the user of obtaining the LDAPS script and instead just have the script import it automatically.

I'll try this out and post an update soon.

Cheers!

**Comment by Zer0CoolX** [comment] 2020-02-12 20:40
Thanks for gathering the info, and your right I see 1.5.0-1.8.0 in `/usr/lib` as well. I do have some ideas but will first explain the code on the lines in question.

The block from 1491 to 1500 is only run when the option for LDAPS was selected from the menu. Line 1491's IF statement evaluates this. If its true, then the code is executed, otherwise its skipped.

Line 1493:
`KS_PATH=$(find "/usr/lib/jvm/" -name "cacerts")`

This line runs the find command to discover the path of the built in, default "cacerts" java keystore.

I would recommend you run the following and see what your output is: find `"/usr/lib/jvm/" -name "cacerts"`. For me this returns: `/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/lib/security/cacerts`

In your OP, the error returned 2 paths instead of one. I think this is the cause of your issue. I am also not sure why your has both and mine only has 1.8.0 returned for this.

Line 1494:
`keytool -storepasswd -new ${JKS_CACERT_PASSWD} -keystore ${KS_PATH} -storepass "changeit"`

This line is used to change the default password of "changeit" on the default, built in keystore "cacerts" at the path provided by line 1493. As described above, I would expect this normally to be a single path related to java 1.8.0.

Line 1495:
`keytool -importcert -alias "ldaps" -keystore ${KS_PATH} -storepass ${JKS_CACERT_PASSWD} -file ${LDAPS_CERT_FULL} -noprompt`

This line imports the LDAPS cert file the user provides (via the LDAPS menu by providing the file name and path of the cert) into the "cacerts" built in/default keystore.

Line 1497:
`echo "ldap-encryption-method: ssl" >> /etc/guacamole/${GUAC_CONF}`

This just adds the entry in the guacamole.properties file required to use LDAPS.

So, to summarize the code in this block does not create a keystore. Basically what happens is:

- Check if LDAPS was selected
- Find the path of the default, built in "cacerts" keystore.
- Change the default password on the default "cacerts" keystore.
- Import the LDAPS cert into the default, built in "cacerts" keystore.
- Update the guacamole.properties file by adding the line needed to enable LDAPS.

I think the issue seems to be that for some reason the find command is returning 2 paths for the cacert, not just the java 1.8.0 one.

I dont see the yum update command being an issue, but the script does run yum update itself anyway so you might consider trying it without updating manually first (as long as your on CentOS 7.7 and not updating minor version from an old ISO in which case I recommend a 7.7 ISO).

If you installed CentOS using some sort of automation, like a kickstart file or ansible, etc. you may want to review it and see if its somehow setting a "path" kind of variable or something for both 1.7.0 and 1.8.0.

As a short term work around, you could replace the find command in the script with the full path for 1.8.0 only and see if it runs without problem that way.

Hope this helps. Let me know what you find or if you think there is a flaw in the script that lead to this.

**Comment by sloanja** [comment] 2020-02-12 20:56
It seems to me based on Zer0CoolX's latest response is that the root cause is multiple Java installations.  How about using a grep command to weed out any java installation that is not 1.8.0 as defined by the installation script?

Perhaps something like:
KS_PATH=$(find "/usr/lib/jvm/" -name "cacerts"|grep "1.8.0")

You could also future proof it by using a variable here instead of "1.8.0" to identify the latest version of Java installed.  The command "java -version" might be able to be parsed, then use that version to find the right path to use.

**Comment by Zer0CoolX** [comment] 2020-02-12 21:11
> It seems to me based on Zer0CoolX's latest response is that the root cause is multiple Java installations.

To clarify a bit more here: by default there are multiple version folders from 1.5.0-1.8.0 in `/usr/lib`. However when I run `sudo yum list installed | grep java` I get the following:

```java-1.8.0-openjdk.x86_64              1:1.8.0.242.b08-0.el7_7         @updates
java-1.8.0-openjdk-headless.x86_64     1:1.8.0.242.b08-0.el7_7         @updates
javamail.noarch                        1.4.6-8.el7                     @base
javapackages-tools.noarch              3.4.1-11.el7                    @base
python-javapackages.noarch             3.4.1-11.el7                    @base
tzdata-java.noarch                     2019c-1.el7                     @updates```

This tells me that somehow, java 1.7.0 was installed on the OP's system and I am guessing every installed version of java on a system will have the default cacert keystore.

However, it does NOT appear that the default is to have multiple versions of java installed. So @justsomeusername2020 you need to look at your install process and see if something is causing both to be installed.

@sloanja , good suggestions. I am curious what `java -version` returns when multiple versions are installed?

However, since a clean, fresh, unaltered RHEL/CentOS 7.7 install should not include multiple versions of java and I dont see evidence of the script installing multiple versions (I am going to further confirm this) then I feel like this is a isolated/circumstantial event.

If I find that there is a risk of this being a common issue, then I will implement changes likely like you describe to try and work around/resolve the matter. Thanks

**Comment by Zer0CoolX** [comment] 2020-02-12 21:26
Another consideration. I have CentOS 7.7 minimal and just checked it pre-run of my script.

java is not pre-installed at all, `yum update` does not install java either.

So, @justsomeusername2020 either:

- my script installed multiple versions of java on your for some reason.
- at least 1 version of java was somehow installed on your system pre-script but post CentOS install resulting in multiple versions being installed.
- Your using CentOS with a GUI, and for some reason it came pre-installed with Java 1.7.0? Its been a while since I tested on CentOS with a GUI, so maybe a specific GUI requires an older version of java which is why multiple are on the system?

Just have to narrow down which scenario you fit in.

**Comment by justsomeusername2020** [comment] 2020-02-13 03:41
First off thanks for the detailed explanation of how the ldapsetup function works in the script, I understand it now.


Yes I think you're correct, my ultimate issue why the script failed with the error is because my CentOS installation returned 2 java paths instead of one:

[admin@localhost jvm]$ find "/usr/lib/jvm/" -name "cacerts"
/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.241-2.6.20.0.el7_7.x86_64/jre/lib/security/cacerts
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/lib/security/cacerts

Also, here's this command you wanted to see:

[admin@localhost jvm]$ java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

I actually installed the GNOME GUI option, and also the common GNOME tools, and maybe the server admin tools option. So yes I'm guilty...I did not read/follow instructions like I should have :)
So that is how java 1.7.0 was added most likely.

The reason why is because I used this machine as a dev box with browser debugger to build me a custom .jar extension to change up the guac web UI with different layout, colors, logos, etc. Way easier on box than scp'ing all of the content back and forth.

So the key is to use CentOS 7.7 minimal then.
I'll just restore my VM snapshot, and then prior to running script I'll use your suggested solution:

"As a short term work around, you could replace the find command in the script with the full path for 1.8.0 only and see if it runs without problem that way. IE: KS_PATH="your full path here"."

I'll report back tomorrow.

Cheers!

**Comment by justsomeusername2020** [comment] 2020-02-13 19:10
So as you suggested, I changed line 1493 to read the following and the install script completed successfully!

Here's what I used:
KS_PATH="/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64/jre/lib/security/cacerts"

I am now able log in to Guacamole using AD accounts, and I verified using Wireshark that the AD authentication is using encrypted LDAPS (tcp 636). 

For the LDAPS certificate, all that was needed was to export the Root CA cert from my LDAP server (an Active Directory domain controller), and point the script to that when prompted. (This allows Guacamole to trust the certificate presented by the domain controller during the SSL/TLS handshake for LDAPS).

However, now that LDAPS was enabled I could not get RDP to work anymore.
While running a "tail -f /var/log/messages", I don't see any rdp logging occurring when I launch a test RDP session.

I also tried a server reboot here, no luck.

So as a test, I ran "sudo vi /etc/guacamole/guacamole.properties" and disabled LDAPS again using the following changes:
ldap-port: 389     <<<This was "636"
ldap-encryption-method: none    <<<This was "ssl"

After restarting gaucd and tomcat, RDP started working fine again, including being able to use the ${GUAC_USER} and ${GUAC_PASSWORD} variables as the logged on user's RDP connection credentials.

So, then I reversed my changes in guacamole.properties to enable LDAPS once more, followed by service restarts, and now suddenly RDP is working fine again with LDAPS enabled. (Also confirmed via Wireshark).

So I'm not sure what was invoked by disabling/re-enabling LDAPS, but whatever that did, it was necessary in order to get RDP to function with LDAP enabled.

So I now have a working installation.

**Comment by justsomeusername2020** [comment] 2020-02-13 19:33
Ok, I think I spoke to soon on my last comment...

Here's actually what's occurring with LDAPS enabled:

On the CentOS server itself, I am able to login to Guacamole with an AD account and RDP works just fine.

However, if I browse to the Guacamole web page from other hosts (not on the CentOS server itself) I'm still able to login with AD account, but the RDP sessions don't launch. There's just a black screen for about 30 seconds, and then I get the timeout message about Home/Reconnect/Logout. 

Again, running a "tail -f /var/log/messages" while the above is occurring, there is no rdp logging occurring when I attempt to launch RDP session on the external hosts.

On my RDP connection properties, I'm using "Security mode: Any" and "Ignore server certificate: checked" options. And neither using static user credentials or the Guac variables (${GUAC_xyz}) makes any difference.

Any clues? I'm stumped right now...

**Comment by justsomeusername2020** [comment] 2020-02-13 20:21
It turns out all of the odd behavior that I described about RDP not working on external hosts when LDAPS is enabled, was actually caused by the browser cache of the external machine I was testing.

Somehow the browser on this Windows PC is hosed, because when I finally thought of testing from multiple other external clients & browsers, RDP works just fine with LDAPS enabled.

So once again I believe I now have a working installation.

Cheers

**Comment by Zer0CoolX** [comment] 2020-02-14 19:14
> So the key is to use CentOS 7.7 minimal then.
Well, I know 100% works with minimal as that's how I typically test it. On a dedicated Guacamole server there is no real need for a DE, it only adds larger attack surface to something that is generally exposed to the internet and adds more complexity for packages and dependencies.

Not sure if you installed the DE post CentOS install yourself or if you selected the Server with GUI option during install.

`The reason why is because I used this machine as a dev box...`

I get it, but I am very clear in my directions this is intended for a clean install on a fresh install of the OS. Complications like this are exactly the reason why.

I am unsure if the default "Server with GUI" installs multiple versions of Java itself or not. Someday when I have time I can check it out.

> was actually caused by the browser cache of the external machine I was testing

Your not doing IT right if browser cache doesn't screw you from time to time lol.

Sounds like your on track I am going to close the issue. Re-open or start a new issue should you face more problems.

**Closed by Zer0CoolX** 2020-02-14 19:14 UTC
Labels: bug
