### ISSUE TITLE
[HELP] Guacamole not loading from Safari and iOS

### ISSUE THREAD

**Issue by zhendosina** [Zer0CoolX/guacamole-install-rhel#116] opened 2020-04-19 21:12 UTC
Hi, i've strange problem, with fresh guacamole install from script. It just do not work on safari and all browsers on ios. I tried and git version and stable, moreover the older install (about year ago from here) works on safari fine. It  logging in guacamole, but when i try to connect to rdp - get black screen, and error, after a number of seconds, server disconnected. Those trouble is appear and in old browsers in windows vista. But, that works fine, under install on ubuntu from here https://github.com/MysticRyuujin/guac-install. Logs are empty. I do not have any ideas more...

**Comment by zhendosina** [comment] 2020-04-19 21:28
A little detail. This is fair for all types of connection in safari. (ssh, telnet,vnc,rdp)

**Comment by zhendosina** [comment] 2020-04-19 21:38
Do not works
<img width="1676" alt="do not work" src="https://user-images.githubusercontent.com/5647365/79700556-33482b00-829f-11ea-9aa1-f3158c6cd70c.png">

**Comment by zhendosina** [comment] 2020-04-19 21:38
works
<img width="1680" alt="works" src="https://user-images.githubusercontent.com/5647365/79700575-4a871880-829f-11ea-9581-b606ce24ade9.png">

**Comment by zhendosina** [comment] 2020-04-19 21:49
works fine (fresh install ubuntu script 1.1.0)
<img width="1678" alt="Снимок экрана 2020-04-20 в 00 47 17" src="https://user-images.githubusercontent.com/5647365/79700752-bae26980-82a0-11ea-87e7-9ad07e3a7e2f.png">

**Comment by zhendosina** [comment] 2020-04-20 08:44
and finally fresh install from script (1.1.0) Do not works :(
<img width="1679" alt="Снимок экрана 2020-04-20 в 11 43 02" src="https://user-images.githubusercontent.com/5647365/79732350-3ae9ed00-82fc-11ea-9444-516b60de1681.png">

**Comment by Zer0CoolX** [comment] 2020-04-20 15:17
The screenshots you provided seem to indicate the issue is related to CSP, Content Security Policy, which are parameters added to the Nginx conf to help increase security. Some browsers are not capable of handling these parameters and thus the page may not load in some browsers.

I added this to the script many months back. There is a menu option to use CSP or not. You may also try commenting out the CSP lines from the guacamole_ssl.conf file and restart the nginx server.

Also, X-FRAME-OPTIONSdetermines if a page can be rendered in an HTTP frame/iframe/object, etc. As far as I know this is not something that happens in a normal setup. If you are trying to load this through an iframe or other similar tag then you have modified the setup and I cannot help regarding that unique setup.

To my knowledge, the other script you linked to does not go to the same efforts I do with my script for security. As such it may work in cases mine does not. I would imagine they do not use CSP in their script.

You can try commenting out or adjusting CSP in your setup to allow for the browsers you need to work. I do not have desktop Safari to test on, but I can test on iOS later to see if it affects me the same.

**Comment by zhendosina** [comment] 2020-04-20 16:19
You are right! Switching off csp in menu, fixed this issue. Thank you! I'll try to change csp in conf file, in the hope that i won't have to reinstall it again.

**Comment by Zer0CoolX** [comment] 2020-04-20 18:21
You can adjust the CSP to your needs or leave it off entirely, though I feel it adds security to the setup and would recommend using the most strict settings possible while still being able to use it. When I am able I will check on iOS in Safari and see if the CSP settings cause me problems as well.

**Comment by zhendosina** [comment] 2020-04-21 07:43
yep, thank you. Switching off csp from .conf file did not give result. But reinstall from script without csp attribute worked like a charm ;) Unfortunately it was necessary to input all connections and users again, but now all ok! Thank you again!
P.S. it have to be cool, if there is easy way to export\import users and connections between different installs of guacamole

**Comment by Zer0CoolX** [comment] 2020-04-21 20:26
> it have to be cool, if there is easy way to export\import users and connections between different installs of guacamole

I agree. There are 2 ways to look at this:

1. Between identical setups (version of Guac, selections, etc.)
2. Upgrading from one version of Guac to another (and/or with a different setup).

In the first scenario you can likely export the data base from 1 instance to another. In the 2nd scenario I have not found a reliable and consistent way to do upgrades. In some cases (like with 0.9.14 to 1.0.0) you cant upgrade, they are just too different.

In both instances, they are outside the scope of my script. My script is already almost 2,000 lines of code without accounting for updates or carrying over database/config stuff. Unfortunately, I have limited time and capabilities and as such am focusing on the scripts goal, doing fresh installs of Guacamole as securely and completely as I can. I am glad no CSP worked out for you. I will report back later if Safari on iOS works for me with CSP on.

**Comment by Zer0CoolX** [comment] 2020-04-21 22:54
I have checked a fresh install of Guacamole using the script with CSP enabled and the page loads and allows me to login without error on the latest iOS/iPadOS using the latest version of Safari.

So I would guess that you either are using older versions of the OS/Browser(s) or you are trying to do something outside of the normal usage of Guacamole, like loading it through an iFrame or something.

**Comment by zhendosina** [comment] 2020-04-22 06:51
magic...no, it just fresh install on centos, without any peculiarities...last osx&ios... But now it works, and it is ok, thank you!

**Comment by Zer0CoolX** [comment] 2020-04-22 15:29
Glad to hear it. I am going to close the issue.

**Closed by Zer0CoolX** 2020-04-22 15:29 UTC
Labels: help
