### ISSUE TITLE
[BUG] Centos 7.7 Fresh Installation results in no RDP functionality

### ISSUE THREAD

**Issue by netburnr** [Zer0CoolX/guacamole-install-rhel#78] opened 2019-09-21 00:54 UTC
Tried to install this today, and in /var/log/messages I get this when trying to make a RDP connection:

Sep 20 19:49:36 rdp guacd[6789]: Support for protocol "rdp" is not installed

It appears the rdp packages no longer work due to a dependency problem.

**Comment by Rahulsharma0810** [comment] 2019-09-21 08:05
I am also having the same issue

**Comment by momochantest** [comment] 2019-09-23 09:36
Using automatic translation

It depends on the compatibility of the version of freerdp that is referenced when compiling.
Try getting freerdp below.Please judge carefully whether it is installed because it seems to have just been released.

https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2019-1291da3fca


Please refer to the procedure.

https://issues.apache.org/jira/browse/GUACAMOLE-249

**Comment by netburnr** [comment] 2019-09-23 14:18
I installed the linked rdp package, no change.

[root@rdp ~]# yum install https://kojipkgs.fedoraproject.org//packages/freerdp1.2/1.2.0/13.el7/x86_64/freerdp1.2-1.2.0-13.el7.x86_64.rpm

Sep 23 09:17:32 rdp guacd[8579]: Support for protocol "rdp" is not installed
Sep 23 09:17:32 rdp guacd: guacd[8579]: WARNING:#011Support for protocol "rdp" is not installed

**Comment by momochantest** [comment] 2019-09-23 14:52
This part of the reference.
https://issues.apache.org/jira/browse/GUACAMOLE-249?focusedCommentId=16934626&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16934626

Please check if freerdp compatible with the current guacamole is installed.
After that, you need to run guacamole-install-rhel.
Yum update is executed while guacamole-install-rhel is running. For this reason,
After manually installing the previous freerdp, you need to exclude freerdp * in yum conf.

Confirmation command
yum list installed | grep rdp
　NG:2.0.0-1.rc4.el7
　OK:1.2.0-13.el7

Download guacamole source to check if guacamole can recognize the installed rdp,
There is also a method to check if freerdp ......... yes is displayed as a result of running configure.

**Comment by Gelap78** [comment] 2019-09-23 16:59
Since it wasn't stated outright in this thread, Guacamole is not compatible with FreeRDP 2.0 or newer.  According to [Michael Jumper's post](https://issues.apache.org/jira/browse/GUACAMOLE-249?focusedCommentId=16935964&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16935964), this issue is worked on now and will be resolved in version Guacamole 1.1.

Thanks to those that posted here and on the Guacamole project, I was able to get it working.  For those looking for a step-by-step, here is what I did.  This is just a re-posting of [F Hatz solution](https://issues.apache.org/jira/browse/GUACAMOLE-249?focusedCommentId=16934626&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16934626) but includes the relevant commands. 

1. Uninstall FreeRDP
`yum remove freerdp-devel`
`yum remove freerdp-libs`
2. Enable the repository containing the older version of FreeRDP
`nano /etc/yum.repos.d/CentOS-Vault.repo`
 a. Scroll down to
 `# C7.6.1810`
`[C7.6.1810-base]`
`name=CentOS-7.6.1810 - Base`
`baseurl=http://vault.centos.org/7.6.1810/os/$basearch/`
`gpgcheck=1`
`gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7`
`enabled=0` 
 b. Change the zero to a one next to `enabled=`
 c. Press ctrl-o to save the change and ctrl-x to exit nano.
3. Install the older version of FreeRDP
`yum install freerdp-devel-1.0.2-15.el7`
4. Disable the repository containing the older version of FreeRDP
`nano /etc/yum.repos.d/CentOS-Vault.repo`
 a. Scroll down to
 `# C7.6.1810`
`[C7.6.1810-base]`
`name=CentOS-7.6.1810 - Base`
`baseurl=http://vault.centos.org/7.6.1810/os/$basearch/`
`gpgcheck=1`
`gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7`
`enabled=1` 
 b. Change the one to a zero next to `enabled=`
 c. Press ctrl-o to save the change and ctrl-x to exit nano.
5. Prevent further updates to FreeRDP
`nano /etc/yum.conf`
   a. Add the following line:  `exclude=freerdp*`
   b. Press ctrl-o to save the change and ctrl-x to exit nano.

**Comment by Zer0CoolX** [comment] 2019-09-23 19:20
Sorry I am just seeing this now. As you guys seem to have figured out, Red Hat updated to freerdp 2.x and there are many programs that depend on 1.x, like Guacamole. There is mention of this in the release notes for CentOS 7.7 here: https://wiki.centos.org/Manuals/ReleaseNotes/CentOS7.1908?action=show&redirect=Manuals%2FReleaseNotes%2FCentOS7 under "Known Issues"

> Red Hat have updated the freerdp packages to the 2.x branch and many things in third party yum repos that build against freerdp will need to be rebuilt to cater for this. ...

As CentOS 8.x should drop tomorrow, I am not yet sure how I will address this. If 8.x requires major alterations to the script, I will likely have a script for 7.x and another script for 8.x (either as 2 files in this repo or by creating a repo just for RHEL/CentOS 8.x).

Once I know how different CentOS 8.x will be, then I can approach how I might fix this in my script(s).

Also, as pointed out, Guacamole 1.1.0 looks like it should resolve this problem as well by supporting freerdp 2.x. Given that my goal is to always support the latest stable release of Guacamole, if Guac 1.1.0 is coming sooner rather than later I may simply update the script for 1.1.0 and not try and resolve issues with previous Guac versions and freerdp 2.x.

Thanks

**Comment by netburnr** [comment] 2019-09-23 23:54
Thank you@Gelap78 for the great instructions.  And thanks @Zer0CoolX for my first bug report experience, very positive experience, and thank you very much for your great work on this project!

**Comment by Rahulsharma0810** [comment] 2019-09-24 07:15
yes the issue is with new Freerdp lib, I uninstalled v2 and tried to install v1 but on centos 7 I got dependencies errors.
I wrote how I fixed it - https://blog.rvsharma.com/installing-apache-guacomole/

**Comment by keimond** [comment] 2019-09-24 15:46
Hey just wanted to provide a quick update, I needed the clipboard plugin which is in freerdp-plugins, so I..

- commented out the `exclude=freerdp*` in `/etc/yum.conf`
- ran `sudo yum install freerdp-plugins --enablerepo=C7.6.1810-base --disablerepo=base --disablerepo=updates`
- uncommented `exclude=freerdp*` in `/etc/yum.conf`

So to reiterate the above instructions provided by Gelap78 from scratch getting freerdp working

1. Uninstall FreeRDP
`yum remove freerdp-devel
yum remove freerdp-libs`
2. Install the older version of FreeRDP
`yum install freerdp-devel-1.0.2-15.el7 --enablerepo=C7.6.1810-base --disablerepo=base --disablerepo=updates`
3. Prevent further updates to FreeRDP
`nano /etc/yum.conf`
3a. Add the following line: `exclude=freerdp*`
3b. Press ctrl-o to save the change and ctrl-x to exit nano.

**Comment by Zer0CoolX** [comment] 2019-09-26 14:10
I am going to mark this solved for the time being, but pin it so others can easily find it.

I will also create a card in the Projects | To-Do to implement a fix within the script for this. My priority at the moment is figuring out how I am going to handle getting the script working with RHEL/CentOS 8.x. Once I wrap my head around how I am going to approach that, it could narrow down options or give me direction for resolving this.

Thanks

**Closed by Zer0CoolX** 2019-09-26 14:10 UTC
Labels: bug

**Comment by Zer0CoolX** [comment] 2019-10-17 20:01
This issue is now resolved without user intervention as of version `2019_10_17` of this script. The script will automatically account for needing freerdp 1.x instead of 2.x and handle it accordingly in RHEL/CentOS 7.7 (and hopefully beyond through all 7.x).

The update will also disable updates to freerdp, to prevent future updates from pushing it to 2.x.

This update does not apply to RHEL/CentOS 8.x. Work is ongoing to evaluate the required changes, test and deliver a working script for 8.x

**Comment by Rahulsharma0810** [comment] 2019-11-05 12:27
> Thank you for sharing @Rahulsharma0810. Would you mind updating your blog to reflect that the issue affects CentOS 7.7 and Guacamole 1.0.0 specifically?
> 
> > Guacamole daemon works in freerdp library v1 but In centos 7, yum installation come with v2.0.0, this breaks RDP functionality.
> 
> Your excerpt above is vague and makes it sound like an ongoing or long term issue. For people running versions of CentOS 7.6 < or for those who are or may run Guacamole 1.1.0 > the issue should not be present.
> 
> Thanks

Sure https://blog.rvsharma.com/streaming-rdp-protocol-over-http-via-guacamole/#supportforprotocolrdpisnotinstalled

**Comment by docop** [comment] 2020-02-07 16:03
Hi, i got behind in time.. So i've tried another before your update and was the same. Now just did 1 new this morning and still issues with rdp, with letsencrypt is set. vnc do still work. I send you the login of the vm in reddit. thanks
