### ISSUE TITLE
[BUG] Script Fails on and Error Handler Reports Itself

### ISSUE THREAD

**Issue by Ninad1989** [Zer0CoolX/guacamole-install-rhel#106] opened 2020-02-28 10:05 UTC
Hi Author,

Thanks for this script.

While executing the script I am facing the issue.

Script getting failed showing below error message.
=========
Configure MariaDB
-Enable & start MariaDB service... [-done-]
-Setting root password for MariaDB... [-done-]
-Harden MariaDB... [-done-]
-Creating Database & User for Guacamole... [-done-]
-Creating Guacamole Tables... [-done-]
-Setting Time Zone Database & Config...

%%% ERROR (Script Failed) | Line 880 | Command: false | Exit code: 1 %%%
=========

Checked log file for details and it is ending up with error message like :
=======
 -Setting Time Zone Database & Config...
guac-install.sh: line 877: wait: pid 8677 is not a child of this shell
guac-install.sh: line 931: [: -gt: unary operator expected

%%% ERROR (Script Failed) | Line 880 | Command: false | Exit code: 1 %%%
=======

I am executing this script on Azure VM having CentOS Linux release 7.7.1908 (Core) | 4CPUs | 16G RAM.

Also I want to know, How the authentication is done. Do script complete eliminate the use of .xml file which is normally used to user mapping and authentication?

Some quick help will be appreciated. 

Do let me know if any additional information is required from my end.

Thanks in advance.

**Comment by rpaesani** [comment] 2020-02-28 14:25
Hi Thanks for this script.

I am facing the issue:
   ----==== INSTALLING GUACAMOLE Stable 1.1.0 ====----

Installing Repos
-EPEL is installed.
-RPMFusion is installed.
-Installing Nginx repo... [-done-]
-Installing libjpeg-turbo repo... [-done-]

Updating CentOS, please wait... [-done-]

Installing Required Dependencies
-Installing required packages... [-done-]

Creating Required Directories... [-done-]

Downloading Guacamole Packages
-Downloading Guacamole Server package for installation... [-done-]
-Downloading Guacamole Client package for installation... [-done-]
-Downloading Guacamole JDBC Extension package for installation... [-done-]
-Downloading MySQL Connector package for installation... [-done-]

Decompressing Guacamole Packages
-Decompressing Guacamole Server source... [-done-]
-Decompressing Guacamole JDBC extension... [-done-]
-Decompressing MySQL Connector... [-done-]

Install Guacamole Server
-Compiling Guacamole Server Stage 1 of 4... [-done-]
-Compiling Guacamole Server Stage 2 of 4... [-done-]
-Compiling Guacamole Server Stage 3 of 4... [-done-]
-Compiling Guacamole Server Stage 4 of 4... [-done-]

Install Guacamole Client
-Moving Guacamole Client... [-done-]

Setup Guacamole
-Generating Guacamole configuration file... [-done-]
-Making required symlinks... [-done-]
-Setup guacd user... [-FAILED-]

%%% ERROR (Script Failed) | Line 1216 | Command: groupadd guacd | Exit code: 9 %%%

**Comment by Zer0CoolX** [comment] 2020-02-28 15:36
@rpaesani Please start a new issue for your own issue and fill it out completely. I have removed the contents of your log to save space in this thread for the OP. Once you open your own thread (or after a period of no action) I will delete your comment here as well as this one.

**Comment by Zer0CoolX** [comment] 2020-02-28 15:52
> Also I want to know, How the authentication is done. Do script complete eliminate the use of .xml file which is normally used to user mapping and authentication?

https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/Guacamole-Install-Script-Features

_MariaDB primary authentication by default, completely configured for use with Apache Guacamole. When using another method of primary authentication MariaDB is used to store user metadata._

So short version, yes the xml mapping approach is eliminated in my script with the default "base" method being the use of a mariadb database with LDAP being another option currently (still stores meta data in mariadb)

Also see: https://guacamole.apache.org/doc/gug/jdbc-auth.html

> Do let me know if any additional information is required from my end.

I will need some more info and for you to check/confirm many things:

1. What options did you pick from the menus during installation? what cert type, what authentication, did you change any Nginx stuff, etc
2. Was this a fresh, clean install of CentOS or had it previously been installed and configured with other software?
3. Did you try running it again, in a new, cleanly setup CentOS VM? Rarely the script can fail for unexplained reasons caused by temporary processes running at that moment. In those cases starting with a fresh instance (or restoring a snapshot) and running the script again ends up working without error.
4. Did you install CentOS manually from a vanilla ISO/image or was this deployed using automated means and/or was this a customized image altered by you or Azure? I cannot test on non-standard images/installs. If the CentOS VM was not installed vanilla try that if you can.
5. If you do attempt again on a clean install of the OS, first try the most basic options from the script you can (typically the defaults). Self signed cert, mariadb auth, no 2FA, no changes to Nginx config. If that works then you try again with additional options (again on a clean OS).
6. Did you edit the script? Lines 877 and 931 you show from the log are both comments in my original code. If so you need to clearly detail what you changed. Also line 880 in my code is an "else" line. Depending on how much you have altered the code I may not be able to help with it.

So please answer the above as clearly and completely as you can. Re-try on a fresh install of CentOS 7.7, go with the most basic (default) options in the script as you can, leaving the script unaltered, and see if that works. If so you can repeat the process trying other options until it either all works or it stops working and then we will have an idea of what specifically is a problem.

**Comment by docop** [comment] 2020-02-29 20:59
If i can add, i install uber amount of time and the recipe : Centos 7 / 7.5 minimal install. No timezone, leave all by default. And the first command to do is : yum update. Then you have a fully up to date version that can run the script fine. But as being a pre-made os on a cloud vps.. try to find a proper minimal install, as all point told by Zer-CoolX

**Comment by Ninad1989** [comment] 2020-03-01 06:47
Hi..
Please find my inline answer for your queries.
>>What options did you pick from the menus during installation? what cert type, what authentication, did you change any Nginx stuff, etc
I have picked up all default options for the installation.  I haven't changes any default setting related to Nginx. also I have chose MariaDB authetication along no SSL cert (install later).

>>Was this a fresh, clean install of CentOS or had it previously been installed and configured with other software?
It is clean CentOS provided by Azure. No other software provided with it.

>>Did you try running it again, in a new, cleanly setup CentOS VM? Rarely the script can fail for unexplained reasons caused by temporary processes running at that moment. In those cases starting with a fresh instance (or restoring a snapshot) and running the script again ends up working without error.
Yes. I tried to install the scripts several times. On CentOS 7.7 as well as RHEL 7. Still giving same result i.e. ending up with error.

>>Did you install CentOS manually from a vanilla ISO/image or was this deployed using automated means and/or was this a customized image altered by you or Azure? I cannot test on non-standard images/installs. If the CentOS VM was not installed vanilla try that if you can.
It is standard CentOS 7.7 provided by azure without any inbuilt softwares/application.

>>If you do attempt again on a clean install of the OS, first try the most basic options from the script you can (typically the defaults). Self signed cert, mariadb auth, no 2FA, no changes to Nginx config. If that works then you try again with additional options (again on a clean OS).
Yes. I have tried it by several different ways, with advanced features and using Basic ones.

>>Did you edit the script? Lines 877 and 931 you show from the log are both comments in my original code. If so you need to clearly detail what you changed. Also line 880 in my code is an "else" line. Depending on how much you have altered the code I may not be able to help with it.
I haven't made any changes in script, this script is downloaded from your repo only and as soon as it gets downloaded I am executing it without making any custom changes.

Still I will try to install it again once after commenting above stated lines and let you know.

Thanks for looking into this will again contact you with the issue if any.

**Comment by Ninad1989** [comment] 2020-03-01 08:22
Hi There,

Again got failure message on execution of script on same configuration with default option and choosing min features. No custome changes in script.

---------
-Setting Time Zone Database & Config...
guac-install.sh: line 878: wait: pid 9092 is not a child of this shell
guac-install.sh: line 932: [: -gt: unary operator expected


%%% ERROR (Script Failed) | Line 881 | Command: false | Exit code: 1 %%%
---------

**Comment by Zer0CoolX** [comment] 2020-03-02 19:30
> I have picked up all default options for the installation. I haven't changes any default setting related to Nginx. also I have chose MariaDB authetication along no SSL cert (install later).

Try running yum update prior to running my script.

Then try using the following setting from the script:

- Database/JKS - all defaults
- Passwords - whatever you want, all 6+ characters
- SSL Cert Type - Self Signed
- Self Signed Cert - defaults
- Nginx - verify LAN IP returned is correct and use IP, NOT a domain/URL. Hostname default, all other Nginx options default.
- Primary Auth MariaDB
- 2FA none.
- Custom extension - no

Things to check for/review:

1. Check the installation log generated by my script. Better yet post it (making sure to remove any sensitive info from it first) after doing the above if it does not work.

The hard part of troubleshooting this is this is the only time the error handler has returned an error that did not point to the actual line failing. The lines you are reporting are in the error handler itself. IE: it like the error handler telling us there was an error vs telling us what error.

Also, I cant be sure if this issue is not Azure related. I do not have the ability to test this script in that environment so I cannot be sure it would/should work there. I can only test in a local VM from an ISO I can confirm is vanilla/untouched.

**Comment by miles2smiles** [comment] 2020-03-03 06:05
Hi,

I have the same error. 

Steps: 
A fresh instal of CentOS 7.7 minimal install 
download the script. 
run the script with al the default values except the domain i changed form localhost to vdi.domain.name

getting the following error on 3 different machines. using VMWare and ProxMox
```

All done!  If you've completed all of the above steps, your MariaDB
installation should now be secure.

Thanks for using MariaDB!

-Creating Database & User for Guacamole...

-Creating Guacamole Tables...
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.

-Setting Time Zone Database & Config...
guac-install.sh: line 878: wait: pid 1712 is not a child of this shell
guac-install.sh: line 932: [: -gt: unary operator expected


%%% ERROR (Script Failed) | Line 881 | Command: false | Exit code: 1 %%%
```

In /var/log/messages.

```Mar  3 09:48:12 centos systemd: Started MariaDB database server.
Mar  3 09:48:20 centos systemd: Stopping MariaDB database server...
Mar  3 09:48:22 centos systemd: Stopped MariaDB database server.
Mar  3 09:48:22 centos systemd: Starting MariaDB database server...
Mar  3 09:48:22 centos mariadb-prepare-db-dir: Database MariaDB is probably initialized in /var/lib/mysql already, nothing is done.
Mar  3 09:48:22 centos mariadb-prepare-db-dir: If this is not the case, make sure the /var/lib/mysql is empty before running mariadb-prepare-db-dir.
Mar  3 09:48:22 centos mysqld_safe: 200303 09:48:22 mysqld_safe Logging to '/var/log/mariadb/mariadb.log'.
Mar  3 09:48:22 centos mysqld_safe: 200303 09:48:22 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
Mar  3 09:48:24 centos systemd: Started MariaDB database server.
```

From the logs I quickly scanned but did not find any errors but here are some of the finding. 


```

------------------------------------------------
guacamole-server version 1.1.0
------------------------------------------------

   Library status:

     freerdp2 ............ yes
     pango ............... yes
     libavcodec .......... yes
     libavutil ........... yes
     libssh2 ............. yes
     libssl .............. yes
     libswscale .......... yes
     libtelnet ........... yes
     libVNCServer ........ yes
     libvorbis ........... yes
     libpulse ............ yes
     libwebsockets ....... yes
     libwebp ............. yes
     wsock32 ............. no

   Protocol support:

      Kubernetes .... yes
      RDP ........... yes
      SSH ........... yes
      Telnet ........ yes
      VNC ........... yes

   Services / tools:

      guacd ...... yes
      guacenc .... yes
      guaclog .... yes

   FreeRDP plugins: /usr/lib64/freerdp2
   Init scripts: no
   Systemd units: /etc/systemd/system

Type "make" to compile guacamole-server.
```

```

-Compiling Guacamole Server Stage 4 of 4...


Install Guacamole Client

-Moving Guacamole Client...
‘client/guacamole.war’ -> ‘/var/lib/guacamole/guacamole.war’


Setup Guacamole

-Generating Guacamole configuration file...

-Making required symlinks...
‘/var/lib/tomcat/webapps/guacamole.war’ -> ‘/var/lib/guacamole/guacamole.war’
‘/usr/share/tomcat/.guacamole/guacamole.properties’ -> ‘/etc/guacamole/guacamole.properties’
‘/usr/share/tomcat/.guacamole/lib’ -> ‘/var/lib/guacamole/lib/’
‘/usr/share/tomcat/.guacamole/extensions’ -> ‘/var/lib/guacamole/extensions/’
‘/usr/lib64/freerdp’ -> ‘/usr/local/lib/freerdp/guac*’

-Setup guacd user...


Configure MariaDB

-Enable & start MariaDB service...
Created symlink from /etc/systemd/system/multi-user.target.wants/mariadb.service to /usr/lib/systemd/system/mariadb.service.

-Setting root password for MariaDB...
```
 
```
 cat guac_tmp_vars

true
```

Let me know if you need more information.

**Comment by Zer0CoolX** [comment] 2020-03-03 15:18
@miles2smiles Thanks for the input, the key seems to be this:

```
-Creating Guacamole Tables...
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
```

For some reason the time zone tables not being setup/created properly. Could be a change in MariaDB or a change in CentOS or a dependent package I am unaware of.

The error appears to really be happening in lines 1265 to 1272, so maybe an issue with the schema files or how they are being pushed to mariaDB? Could someone try changing the script, line 1269 to:

`cat schema/*.sql | mysql -u root -p${MYSQL_PASSWD} -D ${DB_NAME}`

See if that fixes things. Again all defaults, self signed cert, IP (instead of domain), mariadb as auth, no 2FA, default Nginx, no custom extension.

Unfortunately I am very busy right now and am not sure when I can look at this and address it. If the above resolves it I can make the change, if not it might be a while before I can troubleshoot this.

**Comment by Zer0CoolX** [comment] 2020-03-03 20:32
I setup a new CentOS 7.7 minimal VM on a host I do not typically use for testing my script.

I ran the script and it completed without error using the following settings:

- stable
- defaults for database and JKS
- passwords > 6 characters each
- Self signed SSL cert
- default cert size
- default IP for server (**NOT** hostname)
- all other Nginx options default
- mariaDB as primary auth
- no 2FA
- no custom extension

I also got:

```
-Creating Guacamole Tables...
Warning: Unable to load '/usr/share/zoneinfo/leapseconds' as time zone. Skipping it.
Warning: Unable to load '/usr/share/zoneinfo/tzdata.zi' as time zone. Skipping it.
```

In my output but it continued on to completion. I was then able to access and login to the web GUI using the default Guac credentials.

So I am not sure what is falling for you folks. It seems that line 1269 results in the above mentioned 2 lines of output but I think this may be an issue between Guacamoles schema files and the version of mariaDB used by CentOS? I am unsure what the ramifications are, but on the surface seems to be an ignorable thing.

The error you both get is referencing the error handler itself and seems to be trigger during the set of code at lines 1276-1284, but I do not know why.

You can try commenting out lines 1276-1284 and see if the script completes. If so this fix may be breaking for people with certain timezone settings. What time zones are you guys in? Did you set it post-centos install manually or was it automatically selected?

If the script completes without that code, will be interesting to see if authentication on the Guac web GUI still works.

Even with more free time, there is not much more I can do without additional feedback and input from those having this issue to figure out the cause.

**Comment by miles2smiles** [comment] 2020-03-04 05:39
I tried again with commenting line 1276 - 1284

```
----====Gucamole Installation Script====----
       Guacamole Remote Desktop Gateway

   ***        Source Menu     ***

   OS: CentOS 7.7 x86_64
   Stable Version: 1.1.0 || Git Version: 1.2.0

 Pick the desired source to install from (enter 'stable' or 'git', default is 'stable'): stable
   ***     Database and JKS Menu     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 Enter the Guacamole DB name (default guac_db):
 Enter the Guacamole DB username (default guac_adm):
 Enter the Java KeyStore key-size to use (default 4096):

   ***     Passwords Menu     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 Enter the root password for MariaDB: *******
 Enter the Guacamole DB password: *******
 Enter the Guacamole Java KeyStore password, must be 6 or more characters: *******

  ***     SSL Certificate Type Menu     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 What kind of SSL certificate should be used (default 2)?
1) LetsEncrypt
2) Self-signed
3) None
 Enter the number of the desired SSL certificate type: 2


   ***     Self-signed SSL Certificate Menu     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 Enter the Self-Signed SSL key-size to use (default 4096):


  ***     Nginx Menu     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 Enter the LAN IP of this server (default 192.168.1.252):
 Enter a valid hostname or public domain such as mydomain.com (default localhost):
 Enter the URI path, starting and ending with / for example /guacamole/ (default /):
 Use only >= 256-bit SSL ciphers (More secure, less compatible. default: yes)?:
 Use Content-Security-Policy [CSP] (More secure, less compatible. default: yes)?:


   ***     Primary Authentication Extensions Menu     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 What Guacamole extension should be used as the primary user authentication method (default 1)?
1) MariaDB Database
2) LDAP(S)
 Enter the number of the desired authentication method: 1



  ***     2FA Extensions Menu     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 What Guacamole extension should be used as the 2FA authentication method (default 1)?
1) None
2) TOTP
 Enter the number of the desired authentication method: 1


   ***     Custom Extension Summary     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 Install a custom Guacamole extension: false

 Would you like to change these selections (default no)?


   ***     Summary Menu     ***

   OS: CentOS 7.7 x86_64
   Source/Version: Stable 1.1.0

 Select a category to review selections:
1) Database			       6) 2FA Extension
2) Passwords			       7) Custom Extension
3) SSL Cert Type		       8) Accept and Run Installation
4) Nginx			       9) Cancel and Start Over
5) Primary Authentication Extension   10) Cancel and Exit Script
 Enter the number of the category to review: 8
```


Here is the output 


```
-Reloading firewall...
success


SSL Certificate Configuration

-Generating Self-signed SSL Certificate...
Generating a 4096 bit RSA private key
........++
.....................................................................................++
writing new private key to '/etc/nginx/guacamole.key'
-----
-rw-r--r--. 1 root root 3272 Mar  4 09:34 /etc/nginx/guacamole.key

-Changing permissions on SSL private key...
install.sh: line 878: wait: pid 1785 is not a child of this shell
install.sh: line 932: [: -gt: unary operator expected


%%% ERROR (Script Failed) | Line 881 | Command: false | Exit code: 1 %%%
``` 
looking at the script and file permission 


```
[root@centos guac]# ls -alh /etc/nginx/guacamole.key
-r--------. 1 root root 3.2K Mar  4 09:34 /etc/nginx/guacamole.key
```

can you please checck.

**Comment by Zer0CoolX** [comment] 2020-03-04 15:08
@miles2smiles Thank you for taking the time to test it.

What is odd to me here is that it now seemingly fails at a very different time/operation in the script, but still the error handler itself seems to be failing in some way.

I am pretty confident that the SSL self signed key code is correct. Without knowing exactly when the code stops the permissions may not have been adjusted by the script yet (lines 1770).

...

I think I figured out the issues!!! So dumb (of me). I jst updated the script with a potential fix. Please @Ninad1989 and @miles2smiles re-download the updated script and try it again first with the base settings as per the above readout @miles2smiles provided. If that works feel free to try with more advanced settings as desired.

Was a dumb mistake on my part, if I am correct. Embarrassing enough that I hope no one ever checks the diff's on the commit lol.

Thank you guys for your help, please confirm if this fixes the issue for both of you.

**Comment by miles2smiles** [comment] 2020-03-04 16:12
``
SSL Certificate Configuration
-Generating Self-signed SSL Certificate... [-done-]
-Changing permissions on SSL private key... [-done-]
-Enabling SSL certificate in guacamole_ssl.conf... [-done-]

Services
-Restarting all services... [-done-]

##### Installation Complete! #####

Log Files
-Log file: /root/guacamole-1.1.0_04-20-Mar.log
-firewall backup file: /root/guacamole-1.1.0_04-20-Mar.firewall.bkp
```

**Comment by Zer0CoolX** [comment] 2020-03-04 16:45
Thanks for confirming, no clue why it worked for me with the problem and not for some, but should be fixed now then.

**Comment by Ninad1989** [comment] 2020-03-05 06:44
It is working for all basic settings. Guacamole is accessible.
Now, I will try by using some advance settings. Thanks mate for all the changes.
Appreciate your work..!!

**Comment by Zer0CoolX** [comment] 2020-03-05 14:25
@Ninad1989 My pleasure, glad that its working better now. I am going to close the issue. Thanks

**Closed by Zer0CoolX** 2020-03-05 14:25 UTC
Labels: bug
