### ISSUE TITLE
[HELP] Editing install script, install guacamole from mirror which has been edited by myself & hosted.

### ISSUE THREAD

**Issue by digitaldidge** [Zer0CoolX/guacamole-install-rhel#80] opened 2019-10-02 22:51 UTC
**Confirmation of Process**
1. You have read the [How to report issues](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki/How-to-Report-Issues-(Bugs,-Feature-Request-and-Help)) wiki page? Y

2. You read the [wiki](https://github.com/Zer0CoolX/guacamole-install-rhel/wiki), checking all pages for information that may help you? Y

3. You read other requests to ensure this question has not already been asked and/or resolved? Y

**Details**
OS/Version: CENT 7
Guacamole Source: Stable
Any other options selected from the script prompts: N/A

**Error Message(s) and Logs (be sure not to include sensitive/personal information!)**
If an error occurred include the exact message from the display/log. N/A

**Describe the Issue**
Sorry, I'm a little new to github and such.
This is NOT an issue with the .sh script you have kindly produced, that being said it works very well and I would like to delve a little deeper in a slight customisation of my own which mainly relates to a header file or two within the guacamole source code itself.

Could I duplicate the stable guacamole source code, which your script pulls in but modify the header file I need too and then direct the download process to the edited duplicate. While it fetches everything else from wherever it needs.. I notice within the install script that between line numbers 113~128 seems to lead to the download point of guacamole in order to be compiled after the install script collects enough configuration information from the user in order to complete the process. I wish to know if I am going to use the correct syntax.

**Additional context**
I did not wish to pour to much detailed information into this help request, I waffle too much anyway but have a number of customisations I'd like to trial and am willing to go through the process with you in a little more depth, if you have time spare.

Thanks for producing this lovely install script its simplifies the process greatly.

**Comment by Zer0CoolX** [comment] 2019-10-03 13:28
Hello,

If I follow correctly you want to compile Guacamole from modified source that you have made edits to?

Honestly, that's a bit beyond the scope of my script. What specifically are you trying to alter in the source code and why? What files in Guacamole are you changing and how?

The short answer, however, would be I presume you could change the script to install from your desired location. Lines 113-128 basically sets the variables used depending on if you select the stable or git installation source.

If the mirror you have of the Guacamole source is accessible via HTTP/HTTPS then you would likely want to alter any variables related to the git install source to match your mirrors URL's and structure.

I would recommend setting up a VM, snapshot the OS after updates but before running the Guacamole script. Then after modifying the script, run it to test it. If it fails or there is an issue review logs/figure out the cause of the problem, roll back the VM using the snapshot, update the script and then try again. This is essentially the process I use to develop the script.

If you get back to me with what your specifically trying to alter in Guacamole I can try and provide some direction, but as its not really in scope with the script I cant make any promises or devote a ton of time to helping with your specific goals.

**Comment by digitaldidge** [comment] 2019-10-03 14:58
Hello,
Yes indeed, I've mirrored the current  file structure of guacamole version 1.0.0 to my VPS, extracted the guacamole-server-1.0.0.tar.gz modified the /src/guacenc/video.h file to reflect the FPS addition which was currently set to 25 and I'm seeking to improve the FPS on a trial to 35~45 > 60 if at all possible.
`line 35: #define GUACENC_VIDEO_FRAMERATE 25 #current setting`
to
`line 35: #define GUACENC_VIDEO_FRAMERATE 45`
or
`line 35: #define GUACENC_VIDEO_FRAMERATE 60`

But prior to that I've changed the guac-install.sh script to reflect my changes 
`Line 125: GUAC_URL="https://wisecorp.co.uk/guacamole/${GUAC_VER}/"` 

Just testing a fresh install now. I'll keep you posted how it turns out if you'd like :D

**Comment by digitaldidge** [comment] 2019-10-03 15:18
If I manage to get this working, I'll put the gateway online and give you a Windows 10 instance to try out from the location you are to my backend servers for testing out over the IP network :D

*I'll start with 45FPS though and build multiple gateways with varying FPS ranges for comparison. 

-Have a nice day and thanks for getting back to me so soon :D

**Comment by digitaldidge** [comment] 2019-10-03 16:46
Well the install went smoothly (but) RDP was not working at all and an VNC connection to MacOS Mojave was working just fine. I thought to checkout the .log file for the install and very far down within the log I noticed freeRDP was not included for some reason?

-That's not ever happened prior to my knowledge, so I've reverted back to the snapshot and installed freerdp-devel, freerdp-plugins myself and tried to go through the process again. I'm sure I will bump in to various errors taking this path because really the install script loves a complete freshly installed OS to update and install to..

I wonder if you could comment on maybe the reason why FreeRDP was omitted during this install and not that I have ever seen prior? Cannot be just because of a single two digit change within an video.h file, but who knows these days.

-I'll keep you posted, maybe try again tomorrow when I have a little more time :D

**Comment by digitaldidge** [comment] 2019-10-03 18:01
The issue of RDP seems to be related to yum install version 2 of RDP, I'll find all the version 1.0.2 packages/RPMs and install them, then try again tomorrow :D

**Comment by Zer0CoolX** [comment] 2019-10-07 13:26
As for freerdp, here is more info on that topic: https://github.com/Zer0CoolX/guacamole-install-rhel/issues/78

Basically CentOS 7.7 and Guac 1.0.0 require rolling back to or installing freerdp 1.x instead of 2.x as Guacamole currently only works with 1.x.

As for the alteration you are making, have you researched or asked on the Guac mailing lists why that value is hard coded? 25 FPS is an odd choice, they must have had a valid reason for making it 25 instead of ~24/30/60 or even user defined.

In any case it sounds like your on track to make the desired changes. As I mentioned, I cant really be much more help as this is outside of the scope of my script.

**Comment by digitaldidge** [comment] 2019-10-07 13:59
Thanks very much for the reply Zer0CoolX,
I myself while you replied was in the middle of my second recompile of guacamole using the guac-install.sh script I modified to fetch the guacamole-source from my web server with an 60 FPS rating rather then 25 FPS.

My process involved fetching the FreeRDP-1.0.2-15 (FreeRDP, -libs, -devel, -plugins) from another repo and installing them first after a minimal install of CentOS7, editing the guac-install.sh to skip the "update process" and utilise my own offline created repo which seems to have worked because I've only 5 minutes ago logged in via RDP.

-I have to be honest I don't personally see a great increase in FPS from 25 to 60, in-fact.. I cannot really tell between the two as I have multiple guacamole gateways and am testing from within both, however side-by-side is impossible because both cannot be used simultaneously (Windows eh), but the header file modification raising the FPS worked and so to how I went about installing using the guac-install.sh script you provided with a little modification along the way.

I do hope APACHE Guacamole update this software to be compatible with FreeRDPv2 but the API from v1 to v2 of FreeRDP has taken on some huge changes even though it's been released for a fair period of time now.. Typical though, a lovely piece of software gets developed by a known provider to the level of good use, thrown out to the OSS community and then it goes tits up a while later because of updating requirements.

Let's hope this is updated soon and then the script you've produced will become much more viable without any modification until the next huge set of updates come along! ;B 

P.S: I'll also ask about the guac community regarding the FPS lock, but I reckon they should all combine and work through the FreeRDPv2 changes and updates that need patching :D

**Comment by digitaldidge** [comment] 2019-10-07 13:59
I'll let you close off the issue if you like :D

**Comment by Zer0CoolX** [comment] 2019-10-07 19:57
My understanding is Guacamole 1.1.0 should work with freerdp 2.x, but no idea when that will come out.

My script, despite being an ongoing work in progress has worked since Guac 0.9.14 with CentOS ~7.3/4-7.6, it was CentOS 7.7 that moved from freerdp 1.x to 2.x messing everything up :(

Now with CentOS/RHEL 8.x out, I have a lot of work ahead to get things working. Kinda stalled at the moment between life stuff and working out other package issues in CentOS/RHEL 8.x

I am gonna close the issue for now. Thanks

**Closed by Zer0CoolX** 2019-10-07 19:57 UTC
Labels: help
